strict_front_matter: true
livereload: true
lang: en
title: Paolo Umali
email: iam@paolo.ph
description: >- # this means to ignore newlines until "baseurl:"
  This is Paolo Umali's web space. Lorem ipsum dolor sit amet, consectetur
  adipiscing elit. Proin a rhoncus nisi, ut tempus ex. Integer eget est mattis,
  maximus elit sed, scelerisque odio. Maecenas volutpat dui urna, ac viverra.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: huenisys
github_username:  paoloumali

theme: huenited
remote_theme: huenits/huenited

source: jekyll-docs
destination: _site
encoding: utf-8
timezone: Asia/Manila
collections_dir: collections
collections:
  authors:
    output: true

defaults:
  - scope:
      path: "*.html"
      type: "pages"
    values:
      layout: "default"
      permalink: :basename
  - scope:
      path: "*.md"
      type: "pages"
    values:
      layout: "default"
      permalink: :basename
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: post/:year-:month-:day-:title
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      permalink: authors/:title
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - /b
  - /Rakefile
  - /README.md
  - /static.json
  - /public
