name: Jekyll 4 Build & Deploy
description: 'Builds & deploys a Jekyll 4.x site to gh-pages branch of the same repository.'
branding:
  icon: 'package'
  color: 'orange'
runs:
  using: 'docker'
  image: 'jekyll4-deployer/Dockerfile'
