name: Jekyll site CI

on:
  push:
    branches: [ i5-update-theme ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/public:/srv/jekyll/public \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && chmod g+s /srv/jekyll && jekyll build --future"
      env:
        JEKYLL_ENV: production
