name: Jekyll Deploy

on:
  pull_request:
    branches: [ dev ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Bundler Cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Build & Deploy to GitHub Pages
      uses: paoloumali/paoloumali.github.io@i15/pu-jekyll4-deployer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        JEKYLL_DESTINATION: public
        JEKYLL_ENV: production
